### ISSUE TITLE
Reprocessar datas do reveillon

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/wiki#10]
@eng-rodrigocunha detalhar etapas da tarefa (para serem verificadas):

**Comment by fernandascovino** [comment]
Aguardando finalizar o reprocessamento do GPS pelo @eng-rodrigocunha

**Comment by eng-rodrigocunha** [comment]
**Recurso Reveillon 2022-2023**
Verificar com CMO recursos em aberto sobre o tema para corrigir o que for necessário.

**Tratamentos**
1. 2023-12-31 - OS dez/Q2 - Transformar o tipo_dia de Domingo com as informações de Sábado (apenas linhas afetadas Reveillon - shapefile) - Será considerado o período de operação especial de 22h às 5h (a confirmar com SUBP)
2. 2024-01-01 - OS jan/Q1 - Transformar o tipo_dia de Domingo com as informações de Sábado (apenas linhas afetadas Reveillon - shapefile) - Será considerado o período de operação especial de 22h às 5h (a confirmar com SUBP)
3. 2023-12-31 - GTFS de Reveillon + GTFS de dez/Q2 - Na tabela quadro_horario, os serviços serão repetidos com representações de todos os possíveis shapes
4. 2024-01-01 - GTFS de Reveillon + GTFS de jan/Q1 - Na tabela quadro_horario, os serviços serão repetidos com representações de todos os possíveis shapes
5. Modelo DBT deverá ser ajustado para considerar os diferentes shapes (utilizar mesmo modelo do ano anterior)
6. Incluir parâmetros e calendário 2024

**Testes**
1. Para os serviços afetados pelos múltiplos shapes do reveillon, será realizado teste, em dev, para confirmar se a filtragem de viagens foi correta, a saber:
1.1) Filtragem das viagens com mesma chegada e partida pelo maior % de conformidade do shape por `id_veiculo`, `datetime_partida`, `datetime_chegada` ordenada pela maior `perc_conformidade_shape`
1.2) Filtragem das viagens com partida ou chegada diferentes pela maior distancia percorrida por `id_veiculo`, `datetime_partida` ordenada pela `distancia_planejada`
