### ISSUE TITLE
Checar recursos pagos no relatório com o MoviDesk + data lake

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/wiki#45]
- Premissa: Todos os recursos pagos no relatório devem ser atualizados no MoviDesk (a posteriori, D+1 se eu não me engano)
- Teste com os recursos pagos da última quinzena (dez/Q2)

**Comment by lingsv** [comment]
Estou finalizando a apuração, só faltam os consórcios Santa Cruz e Mobirio.

**Comment by lingsv** [comment]
Finalizei a apuração dos recursos. A maior parte dos recursos é da 1ª quinzena de dezembro, que é a última publicada no site da SMTR.

 O João compartilhou comigo uma pasta com os PDFs dos recursos pagos e consegui consultar os relatórios da segunda quinzena de dezembro também, houve apenas um recurso retificado, por pagamento indevido a um dos consórcios.

Todos os recursos foram checados tanto no movidesk quanto no BigQuery. 

Sobre os valores pagos, a CMO está fazendo uma apuração específica sobre isso, então a tabela de DTDI contém as informações relacionadas aos dados capturados e que constam nos relatórios, mas não os valores específicos de cada um.

O link da planilha de apuração é o seguinte: https://docs.google.com/spreadsheets/d/1PsuPT5B8qci9Jni_FQO1FElbIco4T0X6herXpXnFr78/edit?usp=sharing
