### ISSUE TITLE
Responder à demanda MP sobre conferência do subsídio x receita tarifaria

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/wiki#86]
- [ ] Juntar dados pagos via algoritmo com recursos
- [ ] Levantar valor pago por receita tarifaria
- [ ] Gerar tabelas finais

**Comment by fernandascovino** [comment]
Avaliar quinzenas que não coincidem do algoritmo + recursos x relatório com João (CMO)

**Comment by eng-rodrigocunha** [comment]
Tabela https://docs.google.com/spreadsheets/d/1IkF95d0Cou-3K6OlF5k2kVvKu7oVaZd7kq7f-1QKW84/edit?usp=sharing

> Avaliar quinzenas que não coincidem do algoritmo + recursos x relatório com João (CMO)
> 
> [@eng-rodrigocunha](https://github.com/eng-rodrigocunha) construir tabela:
> 
> * quinzena
> * consorcio (uma sem e outra com)
> * subsidio_relatorio
> * recursos_relatorio
> * subsidio_datalake
> * recursos_datalake (backlog)

**Comment by fernandascovino** [comment]
Análises realizadas para responder à demanda entregues ao João (CMO)
